CREATE TABLE book (
    id BIGINT  AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    publicationYear BIGINT NOT NULL,
    isbn VARCHAR(13) NOT NULL,
    CONSTRAINT UQ_BOOK_TITLE_AUTHOR UNIQUE (title, author),
    CONSTRAINT UQ_BOOK_ISBN UNIQUE (isbn)
);

CREATE TABLE patron (
    id BIGINT  AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    mobile VARCHAR(11) NOT NULL,
    email VARCHAR(50) NOT NULL,
    address VARCHAR(255),
    CONSTRAINT UQ_PATRON_MOBILE UNIQUE (mobile),
    CONSTRAINT UQ_PATRON_EMAIL UNIQUE (email)
);

CREATE TABLE borrowing_record (
    id BIGINT  AUTO_INCREMENT PRIMARY KEY,
    book_id BIGINT  NOT NULL,
    patron_id BIGINT NOT NULL,
    borrow_date DATETIME NOT NULL,
    return_date DATETIME,
    CONSTRAINT FK_BORROWING_RECORD_BOOK FOREIGN KEY (book_id) REFERENCES book(id),
    CONSTRAINT FK_BORROWING_RECORD_PATRON FOREIGN KEY (patron_id) REFERENCES patron(id),
    CONSTRAINT UQ_BORROWING_RECORD_BOOK_PATRON UNIQUE (book_id, patron_id)
);
